# Generated by Django 3.1.7 on 2021-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=32)),
                ('modelName', models.CharField(max_length=32)),
                ('yearOfProduction', models.CharField(max_length=8)),
                ('mileage', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('mail', models.CharField(max_length=256)),
            ],
        ),
    ]
