# Generated by Django 3.1.7 on 2021-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sortOrder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
